// Generated by CoffeeScript 1.10.0
(function() {
    var app, express;

    express = require('express');

    app = express();

    app.get('/', function(req, res) {
        return res.send('Hello World');
    });

    app.listen(4000);

}).call(this);
