// Generated by CoffeeScript 1.10.0
(function() {
  var Rx, _requests, app, express, sendHelloWorld;

  express = require('express');

  Rx = require('rx');

  app = express();

  sendHelloWorld = function(e) {
    console.log('sending hello world');
    return e.res.send('Hello World');
  };

  _requests = new Rx.Subject();

  _requests.subscribe(sendHelloWorld);

  app.get('/', function(req, res) {
    return _requests.onNext({
      req: req,
      res: res
    });
  });

  app.listen(3000);

}).call(this);
