// Generated by CoffeeScript 1.10.0
(function() {
  var Rx, _requests, app, express, sendHelloWorld;

  express = require('express');

  Rx = require('rx');

  app = express();

  sendHelloWorld = function(e) {
    return e.res.send('Hello World! query from url: ' + (e.req.query.query || 'nothing'));
  };

  _requests = new Rx.Subject();

  _requests.tap(function(e) {
    return console.log('request to', e.req.url);
  }).subscribe(sendHelloWorld);

  app.get('/', function(req, res) {
    return _requests.onNext({
      req: req,
      res: res
    });
  });

  app.listen(3000);

  exports.app = app;

}).call(this);
